import numpy as np
import pytest


"""

This module tests the molecular integrals, which come out of the compiled extension in
TUNA/tuna_integrals and sit underneath every other result in the program.

Most of the checks are structural, so they hold for any molecule and any basis. The eigenvalues of the
overlap and kinetic energy matrices are also compared against PySCF: eigenvalues do not care what order
the basis functions are stored in, so they can be compared between two programs without having to work
out how each of them lays out its shells.

"""


# Reference calculation used throughout, hydrogen fluoride in 6-31G, which has eleven basis functions

INPUT_LINE = "SPE : H F 0.9168 : HF 6-31G"


# Eigenvalues of the overlap and kinetic energy matrices, from PySCF 2.14.0

OVERLAP_EIGENVALUES = [0.10888491, 0.28358081, 0.39428731, 0.50048307, 0.50048307,
                       0.74596966, 0.98463090, 1.49951693, 1.49951693, 1.69458631, 2.78806010]

LOWEST_KINETIC_EIGENVALUES = [0.10386772, 0.32031316, 0.54421764, 0.78915574]




@pytest.fixture(scope = "module")
def result(tuna):

    """

    Runs the reference calculation once and hands the result to every test in this module.

    """

    return tuna.run(INPUT_LINE)




def test_the_expected_number_of_basis_functions_is_built(result):

    """

    6-31G gives two basis functions for hydrogen and nine for fluorine.

    """

    assert result.integrals.n_basis == 11
    assert result.molecule.n_basis == 11




def test_overlap_matrix_is_symmetric_with_a_unit_diagonal(result):

    """

    Basis functions are normalised, so every diagonal element is one.

    """

    S = result.integrals.S

    assert S == pytest.approx(S.T, abs = 1e-12)
    assert np.diag(S) == pytest.approx(np.ones(S.shape[0]), abs = 1e-10)




def test_overlap_matrix_is_positive_definite(result):

    """

    A linearly independent basis gives an overlap matrix with strictly positive eigenvalues.

    """

    assert np.linalg.eigvalsh(result.integrals.S).min() > 0




def test_overlap_eigenvalues_match_an_independent_reference(result):

    """

    Eigenvalues are independent of basis function ordering, so they can be compared to PySCF directly.

    """

    eigenvalues = np.sort(np.linalg.eigvalsh(result.integrals.S))

    assert eigenvalues == pytest.approx(OVERLAP_EIGENVALUES, abs = 1e-6)




def test_kinetic_energy_matrix_is_symmetric_and_positive_definite(result):

    """

    The kinetic energy operator is positive definite, so all its eigenvalues are positive.

    """

    T = result.integrals.T

    assert T == pytest.approx(T.T, abs = 1e-12)
    assert np.linalg.eigvalsh(T).min() > 0




def test_kinetic_eigenvalues_match_an_independent_reference(result):

    """

    The lowest few eigenvalues of the kinetic energy matrix, against PySCF.

    """

    eigenvalues = np.sort(np.linalg.eigvalsh(result.integrals.T))[:4]

    assert eigenvalues == pytest.approx(LOWEST_KINETIC_EIGENVALUES, abs = 1e-6)




def test_nuclear_attraction_matrix_is_symmetric_and_negative_definite(result):

    """

    Electrons are attracted to positive nuclei, so this matrix has no positive eigenvalues.

    """

    V_NE = result.integrals.V_NE

    assert V_NE == pytest.approx(V_NE.T, abs = 1e-12)
    assert np.linalg.eigvalsh(V_NE).max() < 0




@pytest.mark.parametrize("axes", [(1, 0, 2, 3), (0, 1, 3, 2), (2, 3, 0, 1)])
def test_two_electron_integrals_have_the_expected_permutational_symmetry(result, axes):

    """

    Real basis functions give eight-fold permutational symmetry, generated by these three swaps.

    """

    ERI = result.integrals.ERI_AO

    assert ERI == pytest.approx(ERI.transpose(axes), abs = 1e-12)




def test_two_electron_integrals_are_positive_on_the_diagonal(result):

    """

    A self-repulsion integral is the energy of a charge distribution with itself and cannot be negative.

    """

    ERI = result.integrals.ERI_AO

    assert np.einsum("iiii->i", ERI).min() > 0




def test_density_matrix_traces_to_the_electron_count(result):

    """

    The trace of the density matrix with the overlap matrix counts the electrons.

    """

    trace = np.einsum("ij,ij->", result.density, result.integrals.S)

    assert trace == pytest.approx(result.molecule.n_electrons, abs = 1e-9)




@pytest.mark.parametrize("matrix_name, component_name", [("T", "kinetic_energy"), ("V_NE", "nuclear_electron_energy")])
def test_one_electron_energies_come_from_the_density_and_the_integrals(result, matrix_name, component_name):

    """

    The reported one-electron energy components have to be the contraction of the converged density
    with the corresponding integral matrix. The components are accumulated during the SCF cycle rather
    than recomputed at the end, so they trail the final density by roughly the convergence threshold.

    """

    matrix = getattr(result.integrals, matrix_name)
    energy = np.einsum("ij,ij->", result.density, matrix)

    assert energy == pytest.approx(getattr(result.scf_output, component_name), abs = 1e-6)




def test_nuclear_repulsion_energy_is_the_classical_coulomb_energy(result):

    """

    The total energy less the electronic components is the nuclear repulsion, which for a diatomic is
    just the product of the charges over the separation.

    """

    scf_output = result.scf_output
    molecule = result.molecule

    electronic_energy = (scf_output.kinetic_energy + scf_output.nuclear_electron_energy
                         + scf_output.coulomb_energy + scf_output.exchange_energy + scf_output.correlation_energy)

    expected = molecule.charges[0] * molecule.charges[1] / molecule.bond_length

    assert scf_output.energy - electronic_energy == pytest.approx(expected, abs = 1e-9)
