name: Build and publish wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.12
            cibw-build: cp312-manylinux_x86_64
          - os: macos-latest
            python-version: 3.12
            cibw-build: cp312-macosx_*
          - os: windows-latest
            python-version: 3.12
            cibw-build: cp312-win_amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_SKIP: "*-win32"
          CIBW_BEFORE_BUILD: >
            python -m pip install -U pip setuptools wheel cython &&
            python -m pip install --only-binary=:all: numpy>=1.26 scipy>=1.11.0
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
          if-no-files-found: error

      - name: Build sdist
        if: runner.os == 'Linux'
        run: |
          python -m pip install build
          python -m build --sdist

      - name: Upload sdist
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: ignore

  publish:
    needs: build-wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true

      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: .

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: .
