name: Build and publish wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel twine

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload to PyPI
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload wheelhouse/*
