name: Build and publish wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.12
            cibw-build: cp312-manylinux_x86_64
          - os: ubuntu-latest
            python-version: 3.13
            cibw-build: cp313-manylinux_x86_64
          - os: macos-latest
            python-version: 3.12
            cibw-build: cp312-macosx_*
          - os: macos-latest
            python-version: 3.13
            cibw-build: cp313-macosx_*
          - os: windows-latest
            python-version: 3.12
            cibw-build: cp312-win_amd64
          - os: windows-latest
            python-version: 3.13
            cibw-build: cp313-win_amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install cibuildwheel and twine
        run: python -m pip install --upgrade pip cibuildwheel twine

      - name: Build wheels
        env:

          CIBW_BUILD: ${{ matrix.cibw_build }}

          CIBW_ARCHS_WINDOWS: "AMD64"

          CIBW_SKIP: "*-win32"
          # ensure SciPy/Numpy are binary wheels and available before build
          CIBW_BEFORE_BUILD: >
            python -m pip install -U pip setuptools wheel cython &&
            python -m pip install --only-binary=:all: numpy>=1.26 scipy>=1.11.0
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload to PyPI
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload wheelhouse/*