name: Build and publish wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]

steps:
  - uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"
      architecture: "x64"

  - name: Install cibuildwheel
    run: python -m pip install --upgrade pip cibuildwheel twine

  - name: Build wheels
    env:
      # build only CPython 3.12
      CIBW_BUILD: "cp312-*"
      # avoid 32-bit Windows; only build win_amd64
      CIBW_ARCHS_WINDOWS: "AMD64"
      # belt-and-suspenders: also skip any win32 tags
      CIBW_SKIP: "*-win32"
      # ensure SciPy/Numpy are binary wheels and available before build
      CIBW_BEFORE_BUILD: >
        python -m pip install -U pip setuptools wheel cython &&
        python -m pip install --only-binary=:all: numpy scipy==1.16.0
    run: python -m cibuildwheel --output-dir wheelhouse

  - name: Upload to PyPI
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    run: python -m twine upload wheelhouse/*