name: Build and publish wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies on Linux/macOS
      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install --upgrade numpy cython
          python -m pip install --upgrade scipy

      # Install dependencies on Windows
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install numpy cython
          python -m pip install scipy==1.16.0

      - name: Install cibuildwheel
        run: python -m pip install --upgrade cibuildwheel twine

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload to PyPI
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload wheelhouse/*
